version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "06:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.445.0
    - 1.452.0
    - 1.457.0
    - 1.460.0
    - 1.471.0
    - 1.483.0
    - 1.500.0
    - 1.509.0
    - 1.521.0
    - 1.529.0
  - dependency-name: "@typescript-eslint/typescript-estree"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@sentry/node"
    versions:
    - 6.0.2
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
  - dependency-name: "@types/eslint"
    versions:
    - 7.2.6
    - 7.2.7
    - 7.2.8
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.30
    - 14.14.33
    - 14.14.35
    - 14.14.36
    - 14.14.37
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@types/pg"
    versions:
    - 7.14.10
    - 7.14.9
  - dependency-name: "@types/ws"
    versions:
    - 7.4.0
